# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b27ba78799b9817698046545dd2ad1b80330cc9b49eca6e6b0813f0f1c8f8b6116e45d30221dc5433bdfbffc97f69cfbf99ab54ebe660db6ecb53b1f7f4f7fd9

test:
  secret_key_base: ef063d86dda7471fccb44ca22c09c69f15b7d20148cd97d4f2f8e944b66d364342b3e713e4fd9b5982b5dca4bcf5f89aee8baed0279088a5c8accc0377a1d1a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
